// Code generated by protocol/code_generate.go; DO NOT EDIT.

package protocol

import (
	"google.golang.org/protobuf/proto"
	"project/protocol/generate/pb"
	"project/frame"
)

type CSHandler struct {
	HandlerLogin func(body []byte) error
	HandlerCommon func(body []byte) error
}

func (h *CSHandler) BefHandlerLogin(body []byte) error {
	req := &pb.LoginC2S{}
	if err := proto.Unmarshal(body, req); err != nil {
		frame.LogError("Failed to unmarshal protoId: 1, err: %v", err)
		return err
	}
	frame.LogDebug("Received protoId: 1, req: %v", req.String())
	return nil
}
func (h *CSHandler) AftHandlerLogin(res *pb.LoginS2C) error {
	frame.LogDebug("Processed protoId: 1, res: %v", res.String())
	return nil
}

func (h *CSHandler) BefHandlerCommon(body []byte) error {
	req := &pb.CommonC2S{}
	if err := proto.Unmarshal(body, req); err != nil {
		frame.LogError("Failed to unmarshal protoId: 2, err: %v", err)
		return err
	}
	frame.LogDebug("Received protoId: 2, req: %v", req.String())
	return nil
}
func (h *CSHandler) AftHandlerCommon(res *pb.CommonS2C) error {
	frame.LogDebug("Processed protoId: 2, res: %v", res.String())
	return nil
}
